#
# This file is part of GEO Knowledge Hub Feed.
# Copyright 2023 GEO Secretariat.
#
# GEO Knowledge Hub Feed is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

build:
	yarn clean
	yarn build
	mv public/feed .
	mv public/* feed/
	mv feed public/
